### ISSUE TITLE
Blog post on sorting algorithms -  Selection Sort 

### ISSUE THREAD

**Issue by Ruchip16** [Mentro-Org/Mentro-Community-Blog#11]
Write a blog on selection sort algorithm giving proper explanation and don't just copy-paste content from GFG or any site as referring is okay but copying is not ❌ 
So make sure your blog is plagiarism-free and run your blog through [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) once.

**Comment by niyoj** [comment]
@Ruchip16 I want to contribute for this blog post. Can you assign this issue to me?

**Comment by LoopThrough-i-j** [comment]
[This](https://github.com/Mentro-Org/Mentro-Community-Blog#how-to-contribute-point_down) will help you to get started.

**Comment by niyoj** [comment]
Ok. Will be creating a PR for this issue by 2nd october.

**Comment by niyoj** [comment]
PR done can you please review it and mere the PR if there are no issues.

**Comment by niyoj** [comment]
Here is the new PR #25 for this issue. Sorry have to open a new PR as mistakenly I deleted the forked repo from my GitHub and was unable to force the changes in the previous PR.

**Comment by niyoj** [comment]
@LoopThrough-i-j @Ruchip16 Can you please review my PR and merge it if it has no issues?

**Comment by niyoj** [comment]
@LoopThrough-i-j Thank you. Learned a lot more things practically especially how to work in Jekyll. Now I guess we can close this issue.
