### ISSUE TITLE
How to remove duplicate elements in an sorted array 

### ISSUE THREAD

**Issue by Ruchip16** [Mentro-Org/Mentro-Community-Blog#13]
here is a link to the [leetcode](https://leetcode.com/problems/remove-duplicates-from-sorted-array/) question
Don't just write code but also explain the approaches and write a blog explaining the same.

**Comment by sr33hari** [comment]
Hi, I would like to pick this up, please let me know about the guidelines for the blog.

**Comment by LoopThrough-i-j** [comment]
[Check out the way to contribute.](https://github.com/Mentro-Org/Mentro-Community-Blog/blob/main/contributing.md) Moreover, the blogs should be written in proper English and Should contain a proper explanation of the code.

For Leetcode blogs, use the question number and the name of the question as Title.

**Comment by sr33hari** [comment]
please reassign this task, sorry for the delay.

**Comment by siddharth2411** [comment]
Hi, I would like to take up this task. Can you please assign it to me?

**Comment by LoopThrough-i-j** [comment]
@siddharth2411 please consider writing a blog on something else, there are a ton of other topics you can work on.

**Comment by siddharth2411** [comment]
> @siddharth2411 please consider writing a blog on something else, there are a ton of other topics you can work on.

Can I write a blog on Insertion Sort since there are already 3 blogs in progress on different sorting algorithms? If yes, can you open a new issue?

**Comment by ak-create** [comment]
Hi, I would like to pick this up, please let me know about the guidelines for the blog.

**Comment by LoopThrough-i-j** [comment]
Yes, please create an issue and start working on Insertion Sort. Follow [these](https://github.com/Mentro-Org/Mentro-Community-Blog/blob/main/contributing.md) contribution guidelines, and start contributing. Make sure to ping me or @Ruchip16  in the issue and get yourself assigned.
