### ISSUE TITLE
Adding Auto Commentor on Issues and PR's

### ISSUE THREAD

**Issue by AnirudhPanda** [Mentro-Org/Mentro-Community-Blog#15]
I'll take this!

**Comment by Ruchip16** [comment]
Cool, so should I assign you this?

**Comment by AnirudhPanda** [comment]
> Cool, so should I assign you this?

Haan
And the official label is only  **hackotberfest**  na for issues and Pr?

**Comment by Ruchip16** [comment]
> > Cool, so should I assign you this?
> 
> Haan And the official label is only **hackotberfest** na for issues and Pr?

Yes
