### ISSUE TITLE
Selection Sort in Homepage

### ISSUE THREAD

**Issue by AnirudhPanda** [Mentro-Org/Mentro-Community-Blog#28]
The section should be inside DSA I suppose

![image](https://user-images.githubusercontent.com/66218496/135725538-7138bec6-5db6-4987-bf6c-ecddb335b6b7.png)

**Comment by Ruchip16** [comment]
> The section should be inside DSA I suppose
> 
> ![image](https://user-images.githubusercontent.com/66218496/135725538-7138bec6-5db6-4987-bf6c-ecddb335b6b7.png)

Yaa it was supposed to be under DSA category

**Comment by LoopThrough-i-j** [comment]
Actually as Far as I know the top part will consist of 4 latest blogs... irrespective of all categories

**Comment by LoopThrough-i-j** [comment]
This is also present in DSA category

**Comment by Ruchip16** [comment]
> Actually as Far as I know the top part will consist of 4 latest blogs... irrespective of all categories

ohhkkayy, ya blogs are there in the respective category too
