### ISSUE TITLE
Insertion Sort

### ISSUE THREAD

**Issue by Ruchip16** [Mentro-Org/Mentro-Community-Blog#35]
Write a blog on insertion sort algorithm giving proper explanation and don't just copy-paste content from GFG or any site as referring is okay but copying is not ❌ 
So make sure your blog is plagiarism-free and run your blog through [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) once.

**Comment by TD-17** [comment]
Hey! Could you please assign this issue to me ?

**Comment by Ruchip16** [comment]
> Hey! Could you please assign this issue to me ?

Sure, refer [this](https://github.com/Mentro-Org/Mentro-Community-Blog/blob/main/contributing.md) to get started

**Comment by TD-17** [comment]
@Ruchip16 Please review my PR. 
https://github.com/Mentro-Org/Mentro-Community-Blog/pull/41/commits/52e4c1981ed3ed7b6f36519a4ac0f8078b2e0c95

**Comment by TD-17** [comment]
Hey @Ruchip16 ! Why this issue is closed now ? Is there anything I need to do to merge my PR?

**Comment by Ruchip16** [comment]
> Hey @Ruchip16 ! Why this issue is closed now ? Is there anything I need to do to merge my PR?

you can create a PR it would get merged but since digital ocean (hacktoberfest) has now announced that DSA would not get counted as a contribution we are focusing on development and hence closed all the issues related to DSA

**Comment by TD-17** [comment]
Okay
