### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by Ruchip16** [Mentro-Org/Mentro-Community-Blog#38]
Write a blog on quick sort algorithm giving proper explanation and don't just copy-paste content from GFG or any site as referring is okay but copying is not ❌ 
So make sure your blog is plagiarism-free and run your blog through [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) once.

**Comment by indujaaaa** [comment]
Hello @Ruchip16 , can I take this up?

**Comment by Ruchip16** [comment]
> Hello @Ruchip16 , can I take this up?

 Sure go ahead, refer [this](https://github.com/Mentro-Org/Mentro-Community-Blog#how-to-contribute-point_down) to get started
