### ISSUE TITLE
Shell Sort

### ISSUE THREAD

**Issue by Ruchip16** [Mentro-Org/Mentro-Community-Blog#39]
Write a blog on shell sort algorithm giving proper explanation and don't just copy-paste content from GFG or any site as referring is okay but copying is not ❌ 
So make sure your blog is plagiarism-free and run your blog through [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) once.

**Comment by namangirdhar16** [comment]
@Ruchip16 can i work on this?

**Comment by Ruchip16** [comment]
sure, go ahead
