### ISSUE TITLE
Counting Sort

### ISSUE THREAD

**Issue by Ruchip16** [Mentro-Org/Mentro-Community-Blog#40]
Write a blog on counting sort algorithm giving proper explanation and don't just copy-paste content from GFG or any site as referring is okay but copying is not ❌ 
So make sure your blog is plagiarism-free and run your blog through [Grammarly](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen?hl=en) once.

**Comment by Maitryee-Choudhary** [comment]
Hi @Ruchip16 ,
I would like to work on this.
Can you assign me?

**Comment by Ruchip16** [comment]
Sure @Maitryee-Choudhary go ahead
