### ISSUE TITLE
Add Hamburger menu in the homepage

### ISSUE THREAD

**Issue by Ruchip16** [Mentro-Org/Mentro-Community-Blog#53]
The menubar we have now is basic, we are looking forward to the hamburger menu type

You can post your doubts here itself or reach out to us over discord.

**Comment by TD-17** [comment]
Hey @Ruchip16 ! Will you assign this issue to me ?

**Comment by Neenu-12** [comment]
Hi @Ruchip16 , please assign this issue to me.

**Comment by Ruchip16** [comment]
sure, go ahead

**Comment by Neenu-12** [comment]
@Ruchip16  PR is merged please close this issue
